//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DershaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRTAYARLAR
    {
        public int OGRTAYARLARID { get; set; }
        public string OGRTSIFRE { get; set; }
    }
}
