//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DershaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KASA
    {
        public int KASAID { get; set; }
        public Nullable<int> KASAOGRTID { get; set; }
        public string KASATARIH { get; set; }
        public string KASAGELIR { get; set; }
        public string KASAGIDER { get; set; }
        public string KASABILGI { get; set; }
    
        public virtual TBL_OGRETMENLER TBL_OGRETMENLER { get; set; }
    }
}
