//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DershaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOT
    {
        public int NOTID { get; set; }
        public string NOTOGRNO { get; set; }
        public Nullable<int> NOTOGRID { get; set; }
        public string NOTTARIHI { get; set; }
        public Nullable<int> NOTTYT { get; set; }
        public Nullable<int> NOTAYTSAY { get; set; }
        public Nullable<int> NOTAYTSOZ { get; set; }
        public Nullable<int> NOTAYTEA { get; set; }
    
        public virtual TBL_OGRENCILER TBL_OGRENCILER { get; set; }
    }
}
