//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DershaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRETMENLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OGRETMENLER()
        {
            this.TBL_KASA = new HashSet<TBL_KASA>();
        }
    
        public int OGRTID { get; set; }
        public string OGRTAD { get; set; }
        public string OGRTSOYAD { get; set; }
        public string OGRTTC { get; set; }
        public string OGRTTEL { get; set; }
        public string OGRTMAIL { get; set; }
        public string OGRTIL { get; set; }
        public string OGRTILCE { get; set; }
        public string OGRTADRES { get; set; }
        public string OGRTBRANS { get; set; }
        public string OGRTFOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KASA> TBL_KASA { get; set; }
    }
}
